# 1. Feature Flag CRD (OpenFeature)
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: ui-flags
  namespace: default
spec:
  flagSpec:
    flags:
      welcome-message:
        defaultVariant: "default"
        state: ENABLED
        variants:
          default:
            value: "👋 Welcome to the default message!"
          alt:
            value: "🚀 This is an alternate welcome message!"

---
# 2. HTML ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Feature Flag Demo</title>
    </head>
    <body>
      <h1 id="message">Loading message...</h1>
      <script>
        fetch('/evaluate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ flagKey: 'welcome-message', context: {} })
        })
        .then(res => res.json())
        .then(data => {
          document.getElementById('message').innerText = data.value || 'Fallback message';
        })
        .catch(() => {
          document.getElementById('message').innerText = 'Error loading flag.';
        });
      </script>
    </body>
    </html>

---
# 3. Flag config for flagd
apiVersion: v1
kind: ConfigMap
metadata:
  name: open-feature-flagd-config
  namespace: default
data:
  flag-config.json: |
    {
      "flags": {
        "welcome-message": {
          "variants": {
            "default": { "value": "👋 Welcome to the default message!" },
            "alt": { "value": "🚀 This is an alternate welcome message!" }
          },
          "defaultVariant": "default",
          "state": "ENABLED"
        }
      }
    }

---
# 4. Deployment with nginx, flagd, and flag-evaluator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-demo
  labels:
    app: flag-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-demo
  template:
    metadata:
      labels:
        app: flag-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

        - name: flagd
          image: ghcr.io/open-feature/flagd:latest
          args: ["start", "--uri", "file:/flags/flag-config.json"]
          ports:
            - containerPort: 8013
          volumeMounts:
            - name: flags
              mountPath: /flags

        - name: flag-evaluator
          image: theadisoni/feature:latest
          ports:
            - containerPort: 3000
          env:
            - name: FLAGD_SOCKET_PATH
              value: "/tmp/flagd.sock"
          volumeMounts:
            - name: flagd-socket
              mountPath: /tmp

      volumes:
        - name: html
          configMap:
            name: html-content
        - name: flags
          configMap:
            name: open-feature-flagd-config
        - name: flagd-socket
          emptyDir: {}

---
# 5. LoadBalancer Service to expose nginx + flag-evaluator
apiVersion: v1
kind: Service
metadata:
  name: flag-demo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: flag-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: api
      port: 3000
      targetPort: 3000
