---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: ui-flags
  namespace: default
  labels:
    app: open-feature-demo
    app.kubernetes.io/instance: feature-flag
spec:
  flagSpec:
    flags:
      hex-color:
        defaultVariant: yellow
        state: ENABLED
        targeting:
          if:
            - in:
                - "@faas.com"
                - var:
                    - email
            - yellow
            - null
        variants:
          blue: "0d507b"
          green: "2f5230"
          red: "c05543"
          yellow: "d4ac0d"
      new-welcome-message:
        defaultVariant: on
        state: ENABLED
        variants:
          on:
            value: "Fib3r: Math at the speed of the internet!"
          off:
            value: "Welcome to FaaS: Fibonacci as a Service!"

---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: flag-sources
  namespace: default
  labels:
    app: open-feature-demo
spec:
  sources:
    - source: ui-flags
      provider: kubernetes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-deployment
  labels:
    app: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo
  template:
    metadata:
      labels:
        app: open-feature-demo
      annotations:
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: "flag-sources"
    spec:
      containers:
        - name: open-feature-demo
          image: ghcr.io/open-feature/playground-app:v0.16.0
          args: ["flagd"]
          ports:
            - containerPort: 30000
          env:
            - name: FLAGD_PORT_WEB
              value: "30002"

---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-app-service
  labels:
    app: open-feature-demo
spec:
  type: LoadBalancer
  selector:
    app: open-feature-demo
  ports:
    - name: app
      port: 30000
      targetPort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-ui-service
  labels:
    app: open-feature-demo
spec:
  type: LoadBalancer
  selector:
    app: open-feature-demo
  ports:
    - name: flagd
      port: 30002
      targetPort: 8013
