apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: ui-flags
  namespace: default
  labels:
    app: open-feature-demo
    app.kubernetes.io/instance: feature-flag
spec:
  flagSpec:
    flags:
      hex-color:
        defaultVariant: yellow
        state: ENABLED
        targeting:
          if:
            - in:
                - "@faas.com"
                - var:
                    - email
            - yellow
            - null
        variants:
          blue: 0d507b
          green: 2f5230
          red: c05543
          yellow: d4ac0d
      new-welcome-message:
        defaultVariant: on
        state: ENABLED
        variants:
          on:
            value: Fib3r: Math at the speed of the internet!
          off:
            value: Welcome to FaaS: Fibonacci as a Service!
---
# Flags for our backend application
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: app-flags
  labels:
    app: open-feature-demo
spec:
  flagSpec:
    flags:
      fib-algo:
        variants:
          recursive: recursive
          memo: memo
          loop: loop
          binet: binet
        defaultVariant: recursive
        state: ENABLED
        targeting:
          if:
            - in:
                - '@faas.com'
                - var:
                    - email
            - binet
            - null
      use-remote-fib-service:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'off'
---
# Feature flag source custom resource, configuring flagd to source flags from FeatureFlag CRDs
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: flag-sources
  labels:
    app: open-feature-demo
spec:
  sources:
    - source: app-flags
      provider: kubernetes
    - source: ui-flags
      provider: kubernetes
---
# Deployment of a demo-app using our custom resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-deployment
  labels:
    app: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo
  template:
    metadata:
      labels:
        app: open-feature-demo
      annotations:
        openfeature.dev/enabled: 'true'
        openfeature.dev/featureflagsource: 'flag-sources'
    spec:
      containers:
        - name: open-feature-demo
          image: ghcr.io/open-feature/playground-app:v0.16.0 # x-release-please-version
          args:
            - flagd
          ports:
            - containerPort: 30000
          env:
            - name: FLAGD_PORT_WEB
              value: '30002'
---
# Service to expose our application (switched to LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-app-service
  labels:
    app: open-feature-demo
spec:
  type: LoadBalancer
  selector:
    app: open-feature-demo
  ports:
    - port: 30000
      targetPort: 30000
---
# Service to expose flagd for client-side evaluations (switched to LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-ui-service
  labels:
    app: open-feature-demo
spec:
  type: LoadBalancer
  selector:
    app: open-feature-demo
  ports:
    - port: 30002
      targetPort: 8013
